Gemfile, Gemfile.lock, app/models/booking.rb, app/models/review.rb, app/models/service.rb, app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20201116153959_devise_create_users.rb, db/migrate/20201116154729_add_columns_to_user.rb, db/migrate/20201116155357_create_services.rb, db/migrate/20201116155623_delete_photo_url_model_user.rb, db/migrate/20201116161814_create_bookings.rb, db/migrate/20201116162241_create_reviews.rb, db/migrate/20201116163210_remove_service_references_from_review_table.rb, db/migrate/20201116163408_add_booking_references_to_reviews_table.rb, db/schema.rb, test/models/booking_test.rb, test/models/review_test.rb, test/models/service_test.rb, test/models/user_test.rb
Creation: user, booking, service, review
=> Models creation

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
added a navbar and configurated the views of log_in and sign_up
=> navbar and devise config

app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
=> navbar logout login

Gemfile, Gemfile.lock, app/controllers/services_controller.rb, app/views/services/index.html.erb
=> Controller services update index show

app/controllers/services_controller.rb
=> skip authentification

.gitignore, Gemfile, Gemfile.lock, app/controllers/services_controller.rb, app/models/service.rb, app/policies/service_policy.rb, app/views/services/new.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20201117134011_create_active_storage_tables.active_storage.rb, db/schema.rb
Created in the services controller the new and create actions with the new-view
=> controller new and create

app/controllers/services_controller.rb, app/policies/service_policy.rb, app/views/services/show.html.erb
Service controller => method show added 
View => show.html.erb added
=> controller show method added

app/controllers/services_controller.rb, app/views/services/index.html.erb
Modify the services index method to work with pundit, updated the view to display all the services with their characteristics
=> updated services view + linked with pundit

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/application_controller.rb, app/controllers/services_controller.rb, app/views/devise/registrations/new.html.erb, app/views/services/index.html.erb, app/views/services/show.html.erb, app/views/shared/_navbar.html.erb
Card:
-_card.scss
- html index de services
Add link_to
Display photos
input username
=> link_to card input dans new/user display photos

app/controllers/services_controller.rb, app/policies/service_policy.rb, app/views/services/_form.html.erb, app/views/services/edit.html.erb
Fin du CRUD + label du form update + refacto services policy
=> Controller services edit update destroy

app/controllers/services_controller.rb, app/models/service.rb, app/views/services/_form.html.erb, app/views/services/show.html.erb
:index_vers_la_droite:Service Controller
Faire les boutons pour accéder à l’edit et l’update :coche_blanche:
Afficher la photo sur la show :coche_blanche:
Ajouter le bouton destroy + Tester la méthode destroy. :coche_blanche:
Ajouter la validation pour obliger la photo dans le form de la new (service) :coche_blanche:
Ne pas afficher Destroy et Edit so on est pas le user author :coche_blanche:
=> controller-services + show + authorizations

app/controllers/bookings_controller.rb, app/controllers/pages_controller.rb, app/controllers/services_controller.rb, app/models/user.rb, app/policies/booking_policy.rb, app/views/pages/dashboard.html.erb, app/views/services/show.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb, test/policies/booking_policy_test.rb
created bookings controller
bookings : new and create
display booking form only if you are not the service owner
=> booking controller

app/controllers/services_controller.rb, app/views/services/_form.html.erb, app/views/services/show.html.erb, db/migrate/20201118165331_add_price_to_services.rb, db/schema.rb
Add :
- price to model service
- price to #show de service
=> little changement

app/assets/stylesheets/components/_show_card.scss, app/views/services/show.html.erb, package-lock.json, yarn.lock
=> changes in design

app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb
There was a small line between the navbar and the next element of the page, it's now fixed.
=> flashes alert display bug fixed

app/assets/stylesheets/config/_fonts.scss
Added the fonts Bangers et Roboto
=> define fonts of the website

app/assets/stylesheets/components/_show_card.scss, app/views/services/show.html.erb
Improved the show page 
- created a carousel for the photos (we can upload many photos for each service)
- improved the card display
- added some font awesome icons
=> carousel, font-awesome and design card show

app/controllers/services_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/services/_info_window.html.erb
=> pop up markers

app/javascript/components/banner.js, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js
fixed the console js error messages
=> mapbox bug fixed

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/javascript/plugins/init_mapbox.js
Added Bangers & Open Sans to the fonts and changes the priority about the headers (h)
=> changes font

app/javascript/plugins/flatpickr.js, app/views/pages/dashboard.html.erb, app/views/services/index.html.erb, app/views/services/show.html.erb
- fixing issue dashboard
- flatpicker index
=> flatpicker2 and dashboard

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/views/services/index.html.erb, app/views/shared/_navbar.html.erb
=> Map navbar front

app/controllers/pages_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/pages/dashboard.html.erb
Dashboard end fixed, reload page flatpickr bug fixed
=> dashbord fixed + flatpickr

app/assets/stylesheets/components/_avatar.scss, app/views/services/show.html.erb
La photo de celui qui propose le service s'affiche dans la show
=> picture user service

app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_index.scss, app/javascript/plugins/init_mapbox.js, app/views/pages/dashboard.html.erb, app/views/services/index.html.erb, app/views/services/show.html.erb
carousel photo size
map zoom
fixed bug with the avatar photo:
<% if service.user.avatar.attached? %>
<%= cl_image_tag service.user.avatar.key, class: "card-trip-user avatar-bordered" %>
<% else %>
<%= image_tag "joker.jpg" %>
<% end %>
=> Carousel bugs

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/pages/dashboard.html.erb, app/views/services/show.html.erb, app/views/shared/_navbar.html.erb
navbar and avatar pic everywhere
=> Avatar pic
